name: snowflake-devops-demo
 
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
 
  workflow_dispatch:
 
jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Use Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
 
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
 
        run: |
          pip install schemachange
 
          schemachange deploy \
            --account $SF_ACCOUNT \
            --user $SF_USERNAME \
            --password $SF_PASSWORD \
            --role $SF_ROLE \
            --warehouse $SF_WAREHOUSE \
            --database $SF_DATABASE \
            --change-history-table METADATA.SCHEMACHANGE.CHANGE_HISTORY \
            --root-folder $GITHUB_WORKSPACE/migrations
